/**
 * generated by Xtext 2.20.0
 */
package org.mdse.pts.schedule.dsl.generator;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
public class ScheduleGenerator /* implements AbstractGenerator  */{
  public void doGenerate(final /* Resource */Object resource, final /* IFileSystemAccess2 */Object fsa, final /* IGeneratorContext */Object context) {
  }
}
