/*
 * generated by Xtext 2.21.0
 */
package org.mdse.pts.schedule.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractScheduleScopeProvider extends DelegatingScopeProvider {
}
