<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="schedule" nsURI="http://mdse.org/pts/schedule" nsPrefix="schedule">
  <eClassifiers xsi:type="ecore:EClass" name="Schedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkReference" lowerBound="1"
        eType="#//NetworkReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="withDepot" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.mdse.pts.depot/model/Depot.ecore#//Depot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Date">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" eType="#//Day"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Day">
    <eLiterals name="Monday"/>
    <eLiterals name="Tuesday" value="1"/>
    <eLiterals name="Wednesday" value="2"/>
    <eLiterals name="Thursday" value="3"/>
    <eLiterals name="Friday" value="4"/>
    <eLiterals name="Saturday" value="5"/>
    <eLiterals name="Sunday" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="for" lowerBound="1" eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Network"/>
  </eClassifiers>
</ecore:EPackage>
